package com.oatrice.jarwise.ui.theme

import androidx.compose.ui.graphics.Color

// This file is AUTO-GENERATED by scripts/sync_tokens.js
// Do not edit directly. Edit tokens/colors.json instead.

val Gray100 = Color(0xFFF3F4F6)
val Gray400 = Color(0xFF9CA3AF)
val Gray500 = Color(0xFF6B7280)
val Gray700 = Color(0xFF374151)
val Gray800 = Color(0xFF1F2937)
val Gray900 = Color(0xFF111827)
val Gray950 = Color(0xFF030712)
val Blue400 = Color(0xFF60A5FA)
val Blue500 = Color(0xFF3B82F6)
val Cyan400 = Color(0xFF22D3EE)
val Purple400 = Color(0xFFC084FC)
val Purple500 = Color(0xFFA855F7)
val Pink400 = Color(0xFFF472B6)
val Pink500 = Color(0xFFEC4899)
val Orange400 = Color(0xFFFB923C)
val Orange500 = Color(0xFFF97316)
val Emerald500 = Color(0xFF10B981)
val Green400 = Color(0xFF4ADE80)
val Green500 = Color(0xFF22C55E)
val Yellow200 = Color(0xFFFEF08A)
val Yellow400 = Color(0xFFFACC15)
val Yellow500 = Color(0xFFEAB308)
val Red400 = Color(0xFFF87171)
val Red500 = Color(0xFFEF4444)

// Gradients
val GradientBlueToCyan = listOf(Blue500, Cyan400)
